# .goreleaser.yml
version: 2
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Homebrew tap configuration
brews:
  - name: gobble
    # GitHub repository where the formula will be published
    repository:
      owner: shrobon
      name: homebrew-gobble
    # The project's homepage
    homepage: "https://github.com/shrobon/gobble"
    # A brief description of the project
    description: "A super-fast, easy-to-use file downloader written in Go"
    # The license of the project
    license: "Apache-2.0"
    # Test block for the formula
    test: |
      system "#{bin}/gobble", "--help"