# .goreleaser.yml
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

# The 'archives' section is now much cleaner.
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

# The 'snapshot' section is simplified.
snapshot:
  # 'name_template' is removed. GoReleaser uses its default.

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# 'brews' is renamed to 'homebrews'
homebrews:
  - name: gobble
    repository:
      owner: shrobon
      name: homebrew-gobble
    homepage: "https://github.com/shrobon/gobble"
    description: "A super-fast, easy-to-use file downloader written in Go"
    license: "Apache-2.0"
    test: |
      system "#{bin}/gobble", "--help"